// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxButPQcIMa4SqhoxdUrGi98t1_gCf7k',
    appId: '1:812293069262:android:bd8b3f46001c6fd7e0f39f',
    messagingSenderId: '812293069262',
    projectId: 'auth-8b2ab',
    storageBucket: 'auth-8b2ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnL_b3Yvf9akHodmo_EXlFWfDYjN-bVY',
    appId: '1:812293069262:ios:67627cfdc59943b9e0f39f',
    messagingSenderId: '812293069262',
    projectId: 'auth-8b2ab',
    storageBucket: 'auth-8b2ab.appspot.com',
    androidClientId: '812293069262-g4a2kt1r07if6fvbnim6k99taah8ufdv.apps.googleusercontent.com',
    iosClientId: '812293069262-d69ggcfeq4pkj0d3r53ofhuq8494knbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCityTraveller',
  );
}
